/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.pizzaexpress.frontend.productos;

import com.mycompany.pizzaexpress.backend.modelos.Producto;
import com.mycompany.pizzaexpress.backend.servicios.ProductosCrudService;
import javax.swing.JPanel;

/**
 *
 * @author edu
 */
public class ProductoInfo extends javax.swing.JPanel {
    private ProductosPanel panelPadre2;
    private JPanel panelPadre;
    private Producto producto;
    private ProductosCrudService crudService = new ProductosCrudService();

    /**
     * Creates new form producto
     */
    public ProductoInfo(Producto producto, JPanel padre,ProductosPanel padre2 ) {
        initComponents();
        this.panelPadre = padre;
        this.panelPadre2 = padre2;
        this.producto = producto;
        rellenarDatos();
    }

    private void rellenarDatos() {
        this.nombreLbl2.setText(this.producto.getNombre());
        this.descripcionTxt.setText(this.producto.getDescripcion());
        String disponibilidad = "Agotado";
        if(producto.isActivo()){
            disponibilidad = "Disponible";
        }
        this.disponibleTxt.setText(disponibilidad);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombreLbl2 = new javax.swing.JLabel();
        editarLbl = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        disponibleTxt = new javax.swing.JLabel();
        descripcionTxt = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        nombreLbl2.setFont(new java.awt.Font("Fira Sans", 0, 24)); // NOI18N
        nombreLbl2.setForeground(new java.awt.Color(0, 0, 0));
        nombreLbl2.setText("Nombre");

        editarLbl.setBackground(new java.awt.Color(102, 153, 255));
        editarLbl.setFont(new java.awt.Font("Fira Sans", 0, 24)); // NOI18N
        editarLbl.setText("Editar");
        editarLbl.addActionListener(this::editarLblActionPerformed);

        jLabel1.setFont(new java.awt.Font("Fira Sans", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Descripcion:");

        jLabel2.setFont(new java.awt.Font("Fira Sans", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nombre:");

        jLabel3.setFont(new java.awt.Font("Fira Sans", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Stock:");

        disponibleTxt.setFont(new java.awt.Font("Fira Sans", 0, 24)); // NOI18N
        disponibleTxt.setForeground(new java.awt.Color(0, 0, 0));
        disponibleTxt.setText("Nombre");

        descripcionTxt.setBackground(new java.awt.Color(204, 204, 204));
        descripcionTxt.setFont(new java.awt.Font("Fira Sans", 0, 24)); // NOI18N
        descripcionTxt.setForeground(new java.awt.Color(0, 0, 0));
        descripcionTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 153, 255), 2, true));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreLbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(descripcionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(editarLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(disponibleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nombreLbl2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(descripcionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addComponent(editarLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(disponibleTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void editarLblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarLblActionPerformed
        this.panelPadre2.mostrarProductoForm(producto);
    }//GEN-LAST:event_editarLblActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel descripcionTxt;
    private javax.swing.JLabel disponibleTxt;
    private javax.swing.JButton editarLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel nombreLbl2;
    // End of variables declaration//GEN-END:variables
}
