/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.pizzaexpress.frontend.panels_por_rol.cocinero;

import com.mycompany.pizzaexpress.backend.modelos.partida.Partida;
import com.mycompany.pizzaexpress.frontend.FrameBase;
import com.mycompany.pizzaexpress.frontend.partida.PanelFinPartida;
import com.mycompany.pizzaexpress.frontend.partida.PanelPartida;
import java.awt.BorderLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author edu
 */
public class CocineroPanelBase extends javax.swing.JPanel {
    private FrameBase padre;
    /**
     * Creates new form PanelBase_SuperAdmin
     */
    public CocineroPanelBase(FrameBase padre) {
        initComponents();
       iniciarPanel();
       this.padre = padre;
    }
    
    
    public void  cerrarSesion(){
        this.padre.mostrarLogin();
    }
    
    public void reiniciarPanel(){
        limpiarFrame();
        this.iniciarPanel();
    }
    
    private void iniciarPanel(){
        this.setLayout(new BorderLayout());
        this.add(new CocineroPanel(this), BorderLayout.CENTER);
        this.revalidate();
        this.repaint();
    }
    
    /**
     * Inicia el panel de cocinero pero con un mensaje de error
     * @param mensaje 
     */
    public void cancelarPartidaPorError(String mensaje){
        limpiarFrame();
        this.iniciarPanel();
        JOptionPane.showMessageDialog(padre, mensaje);
        
    }
    
    public void mostrarPanelNuevaPartida(){
        limpiarFrame();
        this.add(new PanelPartida(this), BorderLayout.CENTER);
        this.revalidate();
        this.repaint();
    }
    
    public void irAlPanelFinPartida(Partida partida){
        limpiarFrame();
        this.add(new PanelFinPartida(partida, this), BorderLayout.CENTER);
        this.revalidate();
        this.repaint();
    }
    
    
    public void limpiarFrame(){
        this.removeAll();
        this.revalidate();
        this.repaint();
    }
    
    
    public void regresar(){
        limpiarFrame();
        iniciarPanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
