/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.pizzaexpress.frontend.partida;

import com.mycompany.pizzaexpress.backend.db.PedidosDB;
import com.mycompany.pizzaexpress.backend.db.ProductosDB;
import com.mycompany.pizzaexpress.backend.db.reportes.ReportesPartidasDB;
import com.mycompany.pizzaexpress.backend.exceptions.ExceptionGenerica;
import com.mycompany.pizzaexpress.backend.modelos.partida.Partida;
import com.mycompany.pizzaexpress.frontend.panels_por_rol.cocinero.CocineroPanelBase;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author edu
 */
public class PanelFinPartida extends javax.swing.JPanel {

    private Partida partida;
    private CocineroPanelBase panelPadre;
    private ReportesPartidasDB reportesPartidas;
    private ProductosDB productosDB;
    private PedidosDB pedidosDB;

    /**
     * Creates new form PanelFinPartida
     */
    public PanelFinPartida(Partida partida, CocineroPanelBase padre) {
        initComponents();
        this.pedidosDB = new PedidosDB();
        this.reportesPartidas = new ReportesPartidasDB();
        this.productosDB = new ProductosDB();

        this.regresarBtn.setEnabled(false);
        this.partida = partida;
        this.panelPadre = padre;
        this.lblTitulo.setForeground(Color.red);
        this.lblTitulo.setText(" Espere.....");

        Timer timer = new Timer(2200, e -> {
            this.guardarPartidaYProductos();
            rellenarEstadisticas();
            this.lblTitulo.setForeground(Color.BLACK);
            this.lblTitulo.setText("Partida Terminada");
            this.regresarBtn.setEnabled(true);
        });
        timer.setRepeats(false);
        timer.start();
    }

    private void guardarPartidaYProductos() {
        try {
            this.productosDB.contarProductosEnPedidos(partida.getListaPedidos());
            this.reportesPartidas.crear(partida);
            this.pedidosDB.registrarPedidosPartida(partida);
        } catch (ExceptionGenerica ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }

    }

    private void rellenarEstadisticas() {
        this.lblCancelados.setText(String.valueOf(partida.getPedidosCancelados()));
        this.lblEntregados.setText(String.valueOf(partida.getPedidosExitosos()));
        this.lblIncompletos.setText(String.valueOf(partida.getPedidosIncompletos()));
        this.lblNivel.setText(String.valueOf(partida.getNivelActual()));
        this.lblPuntosNetos.setText(String.valueOf(partida.getPuntosTotales()));
        this.lblPenalizaciones.setText(String.valueOf(partida.getPenalizaciones()));
        this.lblPUntosEficiencia.setText(String.valueOf(partida.getBonosPorEficiencia()));
        this.repaint();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTiempo1 = new javax.swing.JLabel();
        lblPuntosEficiencia = new javax.swing.JLabel();
        lblTiempo3 = new javax.swing.JLabel();
        lblTiempo4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblTiempo = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblIncompletos = new javax.swing.JLabel();
        lblCancelados = new javax.swing.JLabel();
        lblEntregados = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        lblPuntosNetos = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblNivel = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblPUntosEficiencia = new javax.swing.JLabel();
        lblPenalizaciones = new javax.swing.JLabel();
        regresarBtn = new javax.swing.JButton();

        lblTiempo1.setBackground(new java.awt.Color(0, 0, 0));
        lblTiempo1.setFont(new java.awt.Font("Fira Sans", 0, 60)); // NOI18N
        lblTiempo1.setForeground(new java.awt.Color(0, 0, 0));
        lblTiempo1.setText("Fin de partida:");

        lblPuntosEficiencia.setBackground(new java.awt.Color(0, 0, 0));
        lblPuntosEficiencia.setFont(new java.awt.Font("Fira Sans", 0, 36)); // NOI18N
        lblPuntosEficiencia.setForeground(new java.awt.Color(0, 0, 0));
        lblPuntosEficiencia.setText("0");

        lblTiempo3.setBackground(new java.awt.Color(0, 0, 0));
        lblTiempo3.setFont(new java.awt.Font("Fira Sans", 0, 60)); // NOI18N
        lblTiempo3.setForeground(new java.awt.Color(0, 0, 0));
        lblTiempo3.setText("Resumen: ");

        lblTiempo4.setBackground(new java.awt.Color(0, 0, 0));
        lblTiempo4.setFont(new java.awt.Font("Fira Sans", 0, 60)); // NOI18N
        lblTiempo4.setForeground(new java.awt.Color(0, 0, 0));
        lblTiempo4.setText("Fin de partida");

        setBackground(new java.awt.Color(255, 255, 204));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Fira Sans", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Puntos eficiencia:");

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Fira Sans", 0, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Penalizaciones:");

        lblTiempo.setBackground(new java.awt.Color(0, 0, 0));
        lblTiempo.setFont(new java.awt.Font("Fira Sans", 0, 60)); // NOI18N
        lblTiempo.setForeground(new java.awt.Color(0, 0, 0));
        lblTiempo.setText("Pedidos:");

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Fira Sans", 0, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Incompletos:");

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Fira Sans", 0, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Cancelados:");

        lblIncompletos.setBackground(new java.awt.Color(0, 0, 0));
        lblIncompletos.setFont(new java.awt.Font("Fira Sans", 1, 36)); // NOI18N
        lblIncompletos.setForeground(new java.awt.Color(255, 102, 0));
        lblIncompletos.setText("0");

        lblCancelados.setBackground(new java.awt.Color(0, 0, 0));
        lblCancelados.setFont(new java.awt.Font("Fira Sans", 1, 36)); // NOI18N
        lblCancelados.setForeground(new java.awt.Color(255, 51, 51));
        lblCancelados.setText("0");

        lblEntregados.setBackground(new java.awt.Color(0, 0, 0));
        lblEntregados.setFont(new java.awt.Font("Fira Sans", 1, 36)); // NOI18N
        lblEntregados.setForeground(new java.awt.Color(0, 0, 255));
        lblEntregados.setText("0");

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Fira Sans", 0, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Entregados:");

        lbl1.setBackground(new java.awt.Color(0, 0, 0));
        lbl1.setFont(new java.awt.Font("Fira Sans", 0, 36)); // NOI18N
        lbl1.setForeground(new java.awt.Color(0, 0, 0));
        lbl1.setText("Netos:");

        lblPuntosNetos.setBackground(new java.awt.Color(0, 0, 0));
        lblPuntosNetos.setFont(new java.awt.Font("Fira Sans", 1, 36)); // NOI18N
        lblPuntosNetos.setForeground(new java.awt.Color(51, 204, 0));
        lblPuntosNetos.setText("0");

        jLabel14.setBackground(new java.awt.Color(0, 0, 0));
        jLabel14.setFont(new java.awt.Font("Fira Sans", 0, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Nivel:");

        lblNivel.setBackground(new java.awt.Color(0, 0, 0));
        lblNivel.setFont(new java.awt.Font("Fira Sans", 1, 36)); // NOI18N
        lblNivel.setForeground(new java.awt.Color(51, 153, 255));
        lblNivel.setText("1");

        lblTitulo.setBackground(new java.awt.Color(0, 0, 0));
        lblTitulo.setFont(new java.awt.Font("Fira Sans", 0, 60)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lblTitulo.setText("Fin de partida");

        lblPUntosEficiencia.setBackground(new java.awt.Color(0, 0, 0));
        lblPUntosEficiencia.setFont(new java.awt.Font("Fira Sans", 0, 36)); // NOI18N
        lblPUntosEficiencia.setForeground(new java.awt.Color(0, 0, 0));
        lblPUntosEficiencia.setText("0");

        lblPenalizaciones.setBackground(new java.awt.Color(255, 255, 255));
        lblPenalizaciones.setFont(new java.awt.Font("Fira Sans", 0, 36)); // NOI18N
        lblPenalizaciones.setForeground(new java.awt.Color(0, 0, 0));
        lblPenalizaciones.setText("0");

        regresarBtn.setBackground(new java.awt.Color(255, 51, 0));
        regresarBtn.setFont(new java.awt.Font("Fira Sans", 0, 36)); // NOI18N
        regresarBtn.setForeground(new java.awt.Color(0, 0, 0));
        regresarBtn.setText("Regresar");
        regresarBtn.addActionListener(this::regresarBtnActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPenalizaciones)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblNivel)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPUntosEficiencia)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(157, 157, 157)
                                        .addComponent(lblTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(300, 300, 300)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel8))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblEntregados)
                                            .addComponent(lblCancelados)
                                            .addComponent(lblIncompletos))
                                        .addGap(100, 100, 100))))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(regresarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(186, 186, 186)
                    .addComponent(jLabel12)
                    .addGap(162, 162, 162)
                    .addComponent(lbl1)
                    .addGap(18, 18, 18)
                    .addComponent(lblPuntosNetos, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(673, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPUntosEficiencia, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(lblTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIncompletos, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblEntregados, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(lblPenalizaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lblCancelados, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGap(94, 94, 94)))
                .addComponent(regresarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(398, 398, 398)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPuntosNetos, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(280, 280, 280)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void regresarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarBtnActionPerformed
        this.panelPadre.reiniciarPanel();
    }//GEN-LAST:event_regresarBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lblCancelados;
    private javax.swing.JLabel lblEntregados;
    private javax.swing.JLabel lblIncompletos;
    private javax.swing.JLabel lblNivel;
    private javax.swing.JLabel lblPUntosEficiencia;
    private javax.swing.JLabel lblPenalizaciones;
    private javax.swing.JLabel lblPuntosEficiencia;
    private javax.swing.JLabel lblPuntosNetos;
    private javax.swing.JLabel lblTiempo;
    private javax.swing.JLabel lblTiempo1;
    private javax.swing.JLabel lblTiempo3;
    private javax.swing.JLabel lblTiempo4;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JButton regresarBtn;
    // End of variables declaration//GEN-END:variables
}
