/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.pizzaexpress.frontend.reportes;

import com.mycompany.pizzaexpress.backend.db.reportes.ReportesJugadoresDB;
import com.mycompany.pizzaexpress.backend.db.reportes.ReportesPartidasDB;
import com.mycompany.pizzaexpress.backend.exceptions.ExceptionGenerica;
import com.mycompany.pizzaexpress.backend.modelos.Sesion;
import com.mycompany.pizzaexpress.backend.modelos.reportes.PartidaReporte;
import com.mycompany.pizzaexpress.backend.modelos.reportes.UsuarioReporte;
import com.mycompany.pizzaexpress.frontend.panels_por_rol.tendero.TenderoBase;
import com.mycompany.pizzaexpress.frontend.reportes.TablaPartidas;
import com.mycompany.pizzaexpress.frontend.reportes.TablaRanking;
import java.awt.BorderLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author edu
 */
public class ReportesTenderoPanel extends javax.swing.JPanel {

    private ReportesPartidasDB reportesPartidas;
    private ReportesJugadoresDB reportesJugadores;
    private TenderoBase padre;
    private int idSucursal;

    private ArrayList<UsuarioReporte> usuarios;
    private ArrayList<PartidaReporte> partidas;

    /**
     * Creates new form ReportesSucursalPanel
     */
    public ReportesTenderoPanel(TenderoBase panelPadre) {
        initComponents();
        this.padre = panelPadre;
        this.reportesPartidas = new ReportesPartidasDB();
        this.reportesJugadores = new ReportesJugadoresDB();
        this.idSucursal = Sesion.getUsuario().getIdSucursal();
        this.iniciarListas();
    }

    /**
     * Llama al backend para cargar las listas
     */
    private void iniciarListas() {
        try {
            usuarios = this.reportesJugadores.generarRankingSucursal(idSucursal);
            partidas = reportesPartidas.buscarPartidasEnSucursal(idSucursal);
        } catch (ExceptionGenerica ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

    private void mostrarRanking() {
        if (usuarios != null) {
            ponerLayoutPanel();
            this.panelResultados.add(new TablaRanking(usuarios), BorderLayout.CENTER);
            this.refrescarComponentes();
        }
    }

    private void mostrarPartidas() {
        if (partidas != null) {
            ponerLayoutPanel();
            this.panelResultados.add(new TablaPartidas(partidas), BorderLayout.CENTER);
            this.refrescarComponentes();
        }
    }
    
    
    // para dibujar
    private void ponerLayoutPanel() {
        this.panelResultados.removeAll();
        this.panelResultados.setLayout(new BorderLayout());
    }

    private void refrescarComponentes() {
        this.panelResultados.revalidate();
        this.panelResultados.repaint();
        this.revalidate();
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        regresarBtn = new javax.swing.JButton();
        panelResultados = new javax.swing.JPanel();
        regresarBtn1 = new javax.swing.JButton();
        regresarBtn2 = new javax.swing.JButton();
        regresarBtn3 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 204));

        jPanel1.setBackground(new java.awt.Color(255, 204, 153));
        jPanel1.setForeground(new java.awt.Color(255, 153, 0));

        jLabel1.setFont(new java.awt.Font("Fira Sans", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Reportes Sucursal");

        regresarBtn.setBackground(new java.awt.Color(255, 51, 51));
        regresarBtn.setFont(new java.awt.Font("Fira Sans", 0, 36)); // NOI18N
        regresarBtn.setForeground(new java.awt.Color(0, 0, 0));
        regresarBtn.setText("Regresar");
        regresarBtn.addActionListener(this::regresarBtnActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(93, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(regresarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(regresarBtn)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelResultadosLayout = new javax.swing.GroupLayout(panelResultados);
        panelResultados.setLayout(panelResultadosLayout);
        panelResultadosLayout.setHorizontalGroup(
            panelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelResultadosLayout.setVerticalGroup(
            panelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 427, Short.MAX_VALUE)
        );

        regresarBtn1.setBackground(new java.awt.Color(204, 255, 153));
        regresarBtn1.setFont(new java.awt.Font("Fira Sans", 0, 36)); // NOI18N
        regresarBtn1.setForeground(new java.awt.Color(0, 0, 0));
        regresarBtn1.setText("Exportar");

        regresarBtn2.setBackground(new java.awt.Color(204, 204, 204));
        regresarBtn2.setFont(new java.awt.Font("Fira Sans", 0, 36)); // NOI18N
        regresarBtn2.setForeground(new java.awt.Color(0, 0, 0));
        regresarBtn2.setText("Partidas");
        regresarBtn2.addActionListener(this::regresarBtn2ActionPerformed);

        regresarBtn3.setBackground(new java.awt.Color(255, 255, 0));
        regresarBtn3.setFont(new java.awt.Font("Fira Sans", 0, 36)); // NOI18N
        regresarBtn3.setForeground(new java.awt.Color(0, 0, 0));
        regresarBtn3.setText("Ranking ");
        regresarBtn3.addActionListener(this::regresarBtn3ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelResultados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(regresarBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(regresarBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(regresarBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regresarBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(regresarBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(regresarBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(panelResultados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void regresarBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarBtn3ActionPerformed
        this.mostrarRanking();
    }//GEN-LAST:event_regresarBtn3ActionPerformed

    private void regresarBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarBtn2ActionPerformed
        this.mostrarPartidas();
    }//GEN-LAST:event_regresarBtn2ActionPerformed

    private void regresarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarBtnActionPerformed
        this.padre.regresar();
    }//GEN-LAST:event_regresarBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelResultados;
    private javax.swing.JButton regresarBtn;
    private javax.swing.JButton regresarBtn1;
    private javax.swing.JButton regresarBtn2;
    private javax.swing.JButton regresarBtn3;
    // End of variables declaration//GEN-END:variables
}
