/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.pizzaexpress.frontend.reportes;

import com.mycompany.pizzaexpress.backend.modelos.reportes.UsuarioReporte;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author edu
 */
public class TablaRanking extends javax.swing.JPanel {

    /**
     * Creates new form TablaRanking
     */
    public TablaRanking(ArrayList<UsuarioReporte> usuarios) {
        initComponents();
        this.cargarTablaUsuarios(usuarios);
        this.revalidate();
        this.repaint();
        this.componerTabla();
    }

    private void cargarTablaUsuarios(ArrayList<UsuarioReporte> usuarios) {
        DefaultTableModel modelo = (DefaultTableModel) tablaPartida.getModel();
        modelo.setRowCount(0);

        for (UsuarioReporte p : usuarios) {
            Object[] fila = new Object[7];
            fila[0] = p.getNombreSucursal();
            fila[1] = p.getNombre();
            fila[3] = p.getMaxNivel();
            fila[4] = p.getPartidasJugadas();
            fila[5] = p.getPuntosAcumulados();
            fila[6] = p.getPromedioPuntos();

            modelo.addRow(fila);
        }
    }

    private void componerTabla() {
        tablaPartida.getTableHeader().setFont(new java.awt.Font("SansSerif", java.awt.Font.BOLD, 18));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPartida = new javax.swing.JTable();

        tablaPartida.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        tablaPartida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "SUCURSAL", "Jugador", "Nickname", "Nivel max", "Partidas", "Puntos", "Promedio "
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaPartida.setOpaque(false);
        tablaPartida.setRowHeight(35);
        tablaPartida.setRowMargin(1);
        jScrollPane1.setViewportView(tablaPartida);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1186, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaPartida;
    // End of variables declaration//GEN-END:variables
}
