/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.pizzaexpress.frontend.sucursales;

import com.mycompany.pizzaexpress.backend.exceptions.ExceptionGenerica;
import com.mycompany.pizzaexpress.backend.modelos.Sucursal;
import com.mycompany.pizzaexpress.backend.servicios.SucursalesCrudService;
import com.mycompany.pizzaexpress.frontend.panels_por_rol.super_admin.SuperAdminBase;
import java.awt.BorderLayout;
import java.awt.FlowLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author edu
 */
public class SucursalesPanel extends javax.swing.JPanel {

    private SucursalesCrudService crudService = new SucursalesCrudService();
     private SuperAdminBase padre;

    /**
     * Creates new form AdminSucursalPanel
     */
    public SucursalesPanel(SuperAdminBase padre) {
        this.padre = padre;
        initComponents();
        this.setLayout(new BorderLayout());
        //this.add(this.nueva, BorderLayout.NORTH);
        this.add(this.jPanel1, BorderLayout.CENTER);
    }

    public void mostrarSucursalForm(Sucursal sucursal) {
        this.panelResultados.removeAll();
        this.panelResultados.setLayout(new BorderLayout());
        this.panelResultados.add(new NuevaSucursalPanel(this.panelResultados, sucursal), BorderLayout.NORTH);
        this.panelResultados.revalidate();
        this.panelResultados.repaint();
        this.revalidate();
        this.repaint();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barraMenu = new javax.swing.JMenuBar();
        jPanel1 = new javax.swing.JPanel();
        barraBusqeuda = new javax.swing.JTextField();
        buscarBtn = new javax.swing.JButton();
        panelResultados = new javax.swing.JPanel();
        mostrarTodos = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        barraMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                barraMenuMouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        barraBusqeuda.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        barraBusqeuda.addActionListener(this::barraBusqeudaActionPerformed);

        buscarBtn.setBackground(new java.awt.Color(153, 153, 153));
        buscarBtn.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        buscarBtn.setText("Buscar");
        buscarBtn.addActionListener(this::buscarBtnActionPerformed);

        panelResultados.setBackground(new java.awt.Color(204, 204, 0));

        javax.swing.GroupLayout panelResultadosLayout = new javax.swing.GroupLayout(panelResultados);
        panelResultados.setLayout(panelResultadosLayout);
        panelResultadosLayout.setHorizontalGroup(
            panelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelResultadosLayout.setVerticalGroup(
            panelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 313, Short.MAX_VALUE)
        );

        mostrarTodos.setBackground(new java.awt.Color(153, 153, 153));
        mostrarTodos.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        mostrarTodos.setText("Todos");
        mostrarTodos.addActionListener(this::mostrarTodosActionPerformed);

        jButton1.setBackground(new java.awt.Color(51, 102, 255));
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Nueva sucursal");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setBackground(new java.awt.Color(255, 51, 51));
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Regresar");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(barraBusqeuda, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buscarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mostrarTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(29, Short.MAX_VALUE))
            .addComponent(panelResultados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buscarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(barraBusqeuda, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(mostrarTodos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(9, 9, 9)
                .addComponent(panelResultados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void barraBusqeudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barraBusqeudaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barraBusqeudaActionPerformed

    private void barraMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraMenuMouseClicked

    }//GEN-LAST:event_barraMenuMouseClicked

    private void mostrarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarTodosActionPerformed

    }//GEN-LAST:event_mostrarTodosActionPerformed

    private void buscarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarBtnActionPerformed
        try {
            Sucursal sucursal = crudService.getSucursalByName(this.barraBusqeuda.getText());
            this.panelResultados.removeAll();
            this.panelResultados.setLayout(new FlowLayout());
            this.panelResultados.add(new SucursalInfo(sucursal, this.panelResultados, this));
            this.panelResultados.revalidate();
            this.panelResultados.repaint();
            this.revalidate();
            this.repaint();
        } catch (ExceptionGenerica ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_buscarBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.panelResultados.removeAll();
        this.panelResultados.setLayout(new BorderLayout());
        this.panelResultados.add(new NuevaSucursalPanel(this.panelResultados), BorderLayout.NORTH);
        this.panelResultados.revalidate();
        this.panelResultados.repaint();
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.padre.regresar();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField barraBusqeuda;
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JButton buscarBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton mostrarTodos;
    private javax.swing.JPanel panelResultados;
    // End of variables declaration//GEN-END:variables
}
