/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.pizzaexpress.frontend.sucursales;

import com.mycompany.pizzaexpress.backend.exceptions.ExceptionGenerica;
import com.mycompany.pizzaexpress.backend.modelos.Sucursal;
import com.mycompany.pizzaexpress.backend.servicios.SucursalesCrudService;
import com.mycompany.pizzaexpress.frontend.panels_por_rol.AdminSucursalPanel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author edu
 */
public class SucursalInfo extends javax.swing.JPanel {
    private AdminSucursalPanel panelPadre2;
    private JPanel panelPadre;
    private Sucursal sucursal;
    private SucursalesCrudService crudService = new SucursalesCrudService();

    /**
     * Creates new form TablaSucursales
     */
    public SucursalInfo(Sucursal sucursal, JPanel padre,AdminSucursalPanel padre2 ) {
        initComponents();
        this.panelPadre = padre;
        this.panelPadre2 = padre2;
        this.sucursal = sucursal;
        rellenarDatos();
    }

    private void rellenarDatos() {
        this.nombreLbl1.setText(sucursal.getNombre());
        this.ubicacionLbl.setText(sucursal.getUbicacion());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombreLbl1 = new javax.swing.JLabel();
        editarLbl = new javax.swing.JButton();
        eliminarLbl = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ubicacionLbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        nombreLbl1.setFont(new java.awt.Font("Fira Sans", 0, 15)); // NOI18N
        nombreLbl1.setText("Nombre");

        editarLbl.setBackground(new java.awt.Color(102, 153, 255));
        editarLbl.setText("Editar");
        editarLbl.addActionListener(this::editarLblActionPerformed);

        eliminarLbl.setBackground(new java.awt.Color(255, 102, 102));
        eliminarLbl.setText("Eliminar");
        eliminarLbl.addActionListener(this::eliminarLblActionPerformed);

        jLabel1.setFont(new java.awt.Font("Fira Sans", 1, 18)); // NOI18N
        jLabel1.setText("Ubicacion:");

        ubicacionLbl.setFont(new java.awt.Font("Fira Sans", 0, 14)); // NOI18N
        ubicacionLbl.setText("Ubicacion");

        jLabel2.setFont(new java.awt.Font("Fira Sans", 1, 18)); // NOI18N
        jLabel2.setText("Nombre:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(nombreLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ubicacionLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(eliminarLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editarLbl)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(687, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editarLbl)
                    .addComponent(eliminarLbl))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreLbl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addComponent(ubicacionLbl))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addContainerGap()))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void eliminarLblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarLblActionPerformed
        
        int opcion = JOptionPane.showConfirmDialog(this, "Desea eliminar la sucursal?");
        if(opcion == JOptionPane.YES_OPTION){
            try {
                this.crudService.delete(this.sucursal.getId());
                this.panelPadre.removeAll();
                this.panelPadre.repaint();
            } catch (ExceptionGenerica ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }
    }//GEN-LAST:event_eliminarLblActionPerformed

    private void editarLblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarLblActionPerformed
        this.panelPadre2.mostrarSucursalForm(sucursal);
    }//GEN-LAST:event_editarLblActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editarLbl;
    private javax.swing.JButton eliminarLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel nombreLbl1;
    private javax.swing.JLabel ubicacionLbl;
    // End of variables declaration//GEN-END:variables
}
