/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.pizzaexpress.frontend.panels_por_rol;

import com.mycompany.pizzaexpress.backend.exceptions.ExceptionGenerica;
import com.mycompany.pizzaexpress.backend.modelos.Sucursal;
import com.mycompany.pizzaexpress.backend.servicios.SucursalesCrudService;
import com.mycompany.pizzaexpress.frontend.sucursales.NuevaSucursalPanel;
import com.mycompany.pizzaexpress.frontend.sucursales.SucursalInfo;
import java.awt.BorderLayout;
import java.awt.FlowLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author edu
 */
public class AdminSucursalPanel extends javax.swing.JPanel {

    private SucursalesCrudService crudService = new SucursalesCrudService();

    /**
     * Creates new form AdminSucursalPanel
     */
    public AdminSucursalPanel() {
        initComponents();
        this.setLayout(new BorderLayout());
        this.add(this.nueva, BorderLayout.NORTH);
        this.add(this.jPanel1, BorderLayout.CENTER);
    }

    public void mostrarSucursalForm(Sucursal sucursal) {
        this.panelResultados.removeAll();
        this.panelResultados.setLayout(new BorderLayout());
        this.panelResultados.add(new NuevaSucursalPanel(this.panelResultados, sucursal), BorderLayout.NORTH);
        this.panelResultados.revalidate();
        this.panelResultados.repaint();
        this.revalidate();
        this.repaint();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barraMenu = new javax.swing.JMenuBar();
        nueva = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        barraBusqeuda = new javax.swing.JTextField();
        buscarBtn = new javax.swing.JButton();
        panelResultados = new javax.swing.JPanel();
        mostrarTodos = new javax.swing.JButton();

        barraMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                barraMenuMouseClicked(evt);
            }
        });

        nueva.setBorder(new javax.swing.border.MatteBorder(null));
        nueva.setText("Nueva sucursal");
        nueva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nuevaMouseClicked(evt);
            }
        });
        nueva.addActionListener(this::nuevaActionPerformed);
        barraMenu.add(nueva);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        barraBusqeuda.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        barraBusqeuda.addActionListener(this::barraBusqeudaActionPerformed);

        buscarBtn.setBackground(new java.awt.Color(153, 153, 153));
        buscarBtn.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        buscarBtn.setText("Buscar");
        buscarBtn.addActionListener(this::buscarBtnActionPerformed);

        panelResultados.setBackground(new java.awt.Color(204, 204, 0));

        javax.swing.GroupLayout panelResultadosLayout = new javax.swing.GroupLayout(panelResultados);
        panelResultados.setLayout(panelResultadosLayout);
        panelResultadosLayout.setHorizontalGroup(
            panelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelResultadosLayout.setVerticalGroup(
            panelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 313, Short.MAX_VALUE)
        );

        mostrarTodos.setBackground(new java.awt.Color(153, 153, 153));
        mostrarTodos.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        mostrarTodos.setText("Todos");
        mostrarTodos.addActionListener(this::mostrarTodosActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addComponent(barraBusqeuda, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buscarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mostrarTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(panelResultados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(barraBusqeuda, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(buscarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mostrarTodos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addComponent(panelResultados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void barraBusqeudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barraBusqeudaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barraBusqeudaActionPerformed

    private void nuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevaActionPerformed

    }//GEN-LAST:event_nuevaActionPerformed

    private void barraMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraMenuMouseClicked

    }//GEN-LAST:event_barraMenuMouseClicked

    private void nuevaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nuevaMouseClicked
        this.panelResultados.removeAll();
        this.panelResultados.setLayout(new BorderLayout());
        this.panelResultados.add(new NuevaSucursalPanel(this.panelResultados), BorderLayout.NORTH);
        this.panelResultados.revalidate();
        this.panelResultados.repaint();
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_nuevaMouseClicked

    private void mostrarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarTodosActionPerformed

    }//GEN-LAST:event_mostrarTodosActionPerformed

    private void buscarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarBtnActionPerformed
        try {
            Sucursal sucursal = crudService.getSucursalByName(this.barraBusqeuda.getText());
            this.panelResultados.removeAll();
            this.panelResultados.setLayout(new FlowLayout());
            this.panelResultados.add(new SucursalInfo(sucursal, this.panelResultados, this));
            this.panelResultados.revalidate();
            this.panelResultados.repaint();
            this.revalidate();
            this.repaint();
        } catch (ExceptionGenerica ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_buscarBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField barraBusqeuda;
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JButton buscarBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton mostrarTodos;
    private javax.swing.JMenu nueva;
    private javax.swing.JPanel panelResultados;
    // End of variables declaration//GEN-END:variables
}
