/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.pizzaexpress.frontend.sucursales;

import com.mycompany.pizzaexpress.backend.exceptions.ExceptionGenerica;
import com.mycompany.pizzaexpress.backend.modelos.Sucursal;
import com.mycompany.pizzaexpress.backend.servicios.SucursalesCrudService;
import com.mycompany.pizzaexpress.frontend.panels_por_rol.super_admin.SuperAdminBase;
import java.awt.BorderLayout;
import java.util.ArrayList;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author edu
 */
public class SucursalesPanel extends javax.swing.JPanel {

    private SucursalesCrudService crudService = new SucursalesCrudService();
    private SuperAdminBase padre;
    private boolean ultimaBusquedaEsTodo;

    /**
     * Creates new form AdminSucursalPanel
     */
    public SucursalesPanel(SuperAdminBase padre) {
        this.padre = padre;
        initComponents();
        this.setLayout(new BorderLayout());
        //this.add(this.nueva, BorderLayout.NORTH);
        this.add(this.jPanel1, BorderLayout.CENTER);
    }

    public void mostrarSucursalForm(Sucursal sucursal) {
        this.formularioPanel.removeAll();
        this.formularioPanel.setLayout(new BorderLayout());
        this.formularioPanel.add(new NuevaSucursalPanel(this.formularioPanel, sucursal, this), BorderLayout.NORTH);
        this.formularioPanel.revalidate();
        this.formularioPanel.repaint();
        this.revalidate();
        this.repaint();
    }
    
    
    public void  actualizarUltimaBusqueda(){
        if(this.ultimaBusquedaEsTodo){
            this.buscarTodos();
        }else{
            this.buscarPorString();
        }   
    }
    
    
    
    private void buscarPorString(){
        this.ultimaBusquedaEsTodo = false;
        if(this.barraBusqeuda.getText().isBlank()){
            return;
        }
        try {
            Sucursal sucursal = crudService.getSucursalByName(this.barraBusqeuda.getText());
            ArrayList<Sucursal> lista = new ArrayList();
            lista.add(sucursal);
            this.mostrarResultados(lista);
        } catch (ExceptionGenerica ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        
    }
    
    
    private void buscarTodos(){
        this.ultimaBusquedaEsTodo = true;
        this.panelResultados.removeAll();
        try {
            ArrayList<Sucursal> lista = this.crudService.seleccionarTodos();
            this.mostrarResultados(lista);
            
        } catch (ExceptionGenerica ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }
    
    
    private void mostrarResultados(ArrayList<Sucursal> lista){
        this.panelResultados.removeAll();
        this.panelResultados.revalidate();
        this.panelResultados.repaint();
        JPanel contenedor = new JPanel();
            contenedor.setLayout(new BoxLayout(contenedor, BoxLayout.Y_AXIS));
            for (Sucursal sucursal : lista) {
                SucursalInfo tarjeta = new SucursalInfo(sucursal, contenedor, this);
                contenedor.add(tarjeta);
                contenedor.add(Box.createVerticalStrut(10));
            }

            contenedor.revalidate();
            contenedor.repaint();

            JScrollPane scrollPane = new JScrollPane(contenedor);
            scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
            scrollPane.getVerticalScrollBar().setUnitIncrement(16);
            
            panelResultados.setLayout(new BorderLayout());
            panelResultados.add(scrollPane, BorderLayout.CENTER);
            panelResultados.revalidate();
            panelResultados.repaint();
            this.revalidate();
            this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barraMenu = new javax.swing.JMenuBar();
        jPanel1 = new javax.swing.JPanel();
        barraBusqeuda = new javax.swing.JTextField();
        buscarBtn = new javax.swing.JButton();
        panelResultados = new javax.swing.JPanel();
        mostrarTodos = new javax.swing.JButton();
        nuevaBtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        formularioPanel = new javax.swing.JPanel();

        barraMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                barraMenuMouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        barraBusqeuda.setFont(new java.awt.Font("Fira Sans", 0, 36)); // NOI18N
        barraBusqeuda.addActionListener(this::barraBusqeudaActionPerformed);

        buscarBtn.setBackground(new java.awt.Color(153, 153, 153));
        buscarBtn.setFont(new java.awt.Font("Fira Sans", 0, 36)); // NOI18N
        buscarBtn.setText("Buscar");
        buscarBtn.addActionListener(this::buscarBtnActionPerformed);

        panelResultados.setBackground(new java.awt.Color(204, 204, 0));

        javax.swing.GroupLayout panelResultadosLayout = new javax.swing.GroupLayout(panelResultados);
        panelResultados.setLayout(panelResultadosLayout);
        panelResultadosLayout.setHorizontalGroup(
            panelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 484, Short.MAX_VALUE)
        );
        panelResultadosLayout.setVerticalGroup(
            panelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 548, Short.MAX_VALUE)
        );

        mostrarTodos.setBackground(new java.awt.Color(153, 153, 153));
        mostrarTodos.setFont(new java.awt.Font("Fira Sans", 0, 36)); // NOI18N
        mostrarTodos.setText("Todos");
        mostrarTodos.addActionListener(this::mostrarTodosActionPerformed);

        nuevaBtn.setBackground(new java.awt.Color(51, 102, 255));
        nuevaBtn.setFont(new java.awt.Font("Fira Sans", 0, 36)); // NOI18N
        nuevaBtn.setForeground(new java.awt.Color(0, 0, 0));
        nuevaBtn.setText("Nueva sucursal");
        nuevaBtn.addActionListener(this::nuevaBtnActionPerformed);

        jButton2.setBackground(new java.awt.Color(255, 51, 51));
        jButton2.setFont(new java.awt.Font("Fira Sans", 0, 36)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Regresar");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        javax.swing.GroupLayout formularioPanelLayout = new javax.swing.GroupLayout(formularioPanel);
        formularioPanel.setLayout(formularioPanelLayout);
        formularioPanelLayout.setHorizontalGroup(
            formularioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        formularioPanelLayout.setVerticalGroup(
            formularioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(179, Short.MAX_VALUE)
                .addComponent(nuevaBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(barraBusqeuda, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buscarBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mostrarTodos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addGap(178, 178, 178))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(panelResultados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formularioPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(barraBusqeuda)
                        .addComponent(nuevaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(mostrarTodos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buscarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelResultados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(formularioPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void barraBusqeudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barraBusqeudaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barraBusqeudaActionPerformed

    private void barraMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraMenuMouseClicked

    }//GEN-LAST:event_barraMenuMouseClicked

    private void mostrarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarTodosActionPerformed
        this.buscarTodos();
    }//GEN-LAST:event_mostrarTodosActionPerformed

    private void buscarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarBtnActionPerformed
        this.buscarPorString();
    }//GEN-LAST:event_buscarBtnActionPerformed

    private void nuevaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevaBtnActionPerformed
        this.formularioPanel.removeAll();
        this.formularioPanel.setLayout(new BorderLayout());
        this.formularioPanel.add(new NuevaSucursalPanel(this.formularioPanel, this), BorderLayout.NORTH);
        this.formularioPanel.revalidate();
        this.formularioPanel.repaint();
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_nuevaBtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.padre.regresar();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField barraBusqeuda;
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JButton buscarBtn;
    private javax.swing.JPanel formularioPanel;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton mostrarTodos;
    private javax.swing.JButton nuevaBtn;
    private javax.swing.JPanel panelResultados;
    // End of variables declaration//GEN-END:variables
}
