/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.pizzaexpress.frontend.usuarios;
import com.mycompany.pizzaexpress.backend.db.SucursalesDB;
import com.mycompany.pizzaexpress.backend.exceptions.ExceptionGenerica;
import com.mycompany.pizzaexpress.backend.modelos.Sucursal;
import com.mycompany.pizzaexpress.backend.servicios.SucursalesCrudService;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author edu
 */
public class UsuarioForm extends javax.swing.JPanel {

    private JPanel parent;
    private Sucursal sucursal;
    private ArrayList<Sucursal> lista;
    private SucursalesDB sucursalesDB = new SucursalesDB();

    /**
     * Creates new form NuevaSucursalPanel
     */
    public UsuarioForm(JPanel panel) {
        this.iniciarPanel(panel);
        this.SucursalesBox.setEnabled(false);
        this.SucursalesBox.setVisible(false);
        this.sucursalLbl.setVisible(false);
        
        this.cargarSucursales();
    }
    
     private void  cargarSucursales(){
        try {
            // cargar todas las sucursales
            this.lista = sucursalesDB.seleccionarTodos();
            // cambiando de sucursales a nombres
            String[] nombres = lista.stream().map(s -> s.getNombre()) .toArray(String[]::new);
            // ondiendoselo al combo box 
            DefaultComboBoxModel modelo = new DefaultComboBoxModel(nombres);
            this.SucursalesBox.setModel(modelo);
        } catch (ExceptionGenerica ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        
    }

    public UsuarioForm(JPanel panel, Sucursal sc) {
        this.iniciarPanel(panel);
        this.rellenarCampos(sc);
        this.sucursal = sc;
    }

    private void iniciarPanel(JPanel panel) {
        initComponents();
        this.parent = panel;
        this.setSize(new Dimension(830, 590));
    }

    private void rellenarCampos(Sucursal sc) {
        this.nombreTexto.setText(sc.getNombre());
        this.ubicacionTexto.setText(sc.getUbicacion());
    }
    
    
    private void desparecer(){
        this.parent.removeAll();
            this.parent.revalidate();
            this.parent.repaint();
    };

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nombreTexto = new javax.swing.JTextField();
        ubicacionTexto = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        ubicacionTexto1 = new javax.swing.JTextField();
        rolesBox = new javax.swing.JComboBox<>();
        SucursalesBox = new javax.swing.JComboBox<>();
        sucursalLbl = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jTextField2.setText("jTextField1");

        jButton2.setBackground(new java.awt.Color(255, 204, 0));
        jButton2.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        jButton2.setText("Guardar");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Ubuntu Light", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("nickname:");

        jLabel2.setFont(new java.awt.Font("Ubuntu Light", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nombre:");

        nombreTexto.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N

        ubicacionTexto.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        ubicacionTexto.addActionListener(this::ubicacionTextoActionPerformed);

        jButton1.setBackground(new java.awt.Color(255, 204, 0));
        jButton1.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        jButton1.setText("Guardar");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton3.setBackground(new java.awt.Color(255, 102, 102));
        jButton3.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        jButton3.setText("Cancelar");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jLabel3.setFont(new java.awt.Font("Ubuntu Light", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Contraseña:");

        ubicacionTexto1.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        ubicacionTexto1.addActionListener(this::ubicacionTexto1ActionPerformed);

        rolesBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin Sistema", "Tendero", "Cocinero" }));
        rolesBox.addActionListener(this::rolesBoxActionPerformed);

        SucursalesBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        SucursalesBox.addActionListener(this::SucursalesBoxActionPerformed);

        sucursalLbl.setFont(new java.awt.Font("Ubuntu Light", 0, 24)); // NOI18N
        sucursalLbl.setForeground(new java.awt.Color(0, 0, 0));
        sucursalLbl.setText("Sucursal:");

        jLabel5.setFont(new java.awt.Font("Ubuntu Light", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Rol:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(112, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rolesBox, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(sucursalLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SucursalesBox, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(ubicacionTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(31, 31, 31)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nombreTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ubicacionTexto1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ubicacionTexto1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ubicacionTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SucursalesBox, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rolesBox, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sucursalLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ubicacionTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubicacionTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ubicacionTextoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // realmente guardar
        SucursalesCrudService crud = new SucursalesCrudService();
        Sucursal nueva = new Sucursal(this.ubicacionTexto.getText(), this.nombreTexto.getText());
        try {
            if(this.sucursal == null){
                crud.crear(nueva);
            }else{
                nueva.setId(sucursal.getId());
                crud.editar(nueva);
            }
            
            this.desparecer();
        } catch (ExceptionGenerica ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.desparecer();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void ubicacionTexto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubicacionTexto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ubicacionTexto1ActionPerformed

    private void rolesBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rolesBoxActionPerformed
        
        boolean valorDeVisidibilidad = false;
        if(this.rolesBox.getSelectedIndex() >0){
            valorDeVisidibilidad = true;
        }
        this.SucursalesBox.setVisible(valorDeVisidibilidad);
        this.SucursalesBox.setEnabled(valorDeVisidibilidad);
        this.sucursalLbl.setVisible(valorDeVisidibilidad);
        
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_rolesBoxActionPerformed

    private void SucursalesBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SucursalesBoxActionPerformed
        
    }//GEN-LAST:event_SucursalesBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> SucursalesBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField nombreTexto;
    private javax.swing.JComboBox<String> rolesBox;
    private javax.swing.JLabel sucursalLbl;
    private javax.swing.JTextField ubicacionTexto;
    private javax.swing.JTextField ubicacionTexto1;
    // End of variables declaration//GEN-END:variables
}
