/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.pizzaexpress.frontend.usuarios;

import com.mycompany.pizzaexpress.backend.db.SucursalesDB;
import com.mycompany.pizzaexpress.backend.exceptions.ExceptionGenerica;
import com.mycompany.pizzaexpress.backend.modelos.Sucursal;
import com.mycompany.pizzaexpress.frontend.panels_por_rol.super_admin.SuperAdminBase;
import java.awt.BorderLayout;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author edu
 */
public class UsuariosPanel extends javax.swing.JPanel {

    private SuperAdminBase padre;
    private ArrayList<Sucursal> lista;
    private SucursalesDB sucursalesDB = new SucursalesDB();

    /**
     * Creates new form UsuariosPanel
     */
    public UsuariosPanel(SuperAdminBase padre) {
        initComponents();
        this.padre = padre;
        this.cargarSucursales();
        this.cambiarVisivilidadSucursales(); // ocultar al inicio las sucursales

    }
    
    
    private void  cargarSucursales(){
        try {
            // cargar todas las sucursales
            this.lista = sucursalesDB.readAll();
            // cambiando de sucursales a nombres
            String[] nombres = lista.stream().map(s -> s.getNombre()) .toArray(String[]::new);
            // ondiendoselo al combo box 
            DefaultComboBoxModel modelo = new DefaultComboBoxModel(nombres);
            this.sucursalesBox.setModel(modelo);
        } catch (ExceptionGenerica ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }
    
    private void cambiarVisivilidadSucursales(){
        boolean valorDeVisidibilidad = false;
        if(this.rolesBox.getSelectedIndex() >0){
            valorDeVisidibilidad = true;
        }
        this.sucursalLbl.setVisible(valorDeVisidibilidad);
        this.sucursalesBox.setVisible(valorDeVisidibilidad);
        this.sucursalesBox.setEnabled(valorDeVisidibilidad);
        this.revalidate();
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nuevoUsuarioBtn = new javax.swing.JButton();
        mostrarTodos = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        barraBusqeuda = new javax.swing.JTextField();
        sucursalesBox = new javax.swing.JComboBox<>();
        rolesBox = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        panelNuevoUsuario = new javax.swing.JPanel();
        mostrarTodos1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        sucursalLbl = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 153));

        nuevoUsuarioBtn.setBackground(new java.awt.Color(51, 102, 255));
        nuevoUsuarioBtn.setForeground(new java.awt.Color(0, 0, 0));
        nuevoUsuarioBtn.setText("Nuevo usuario");
        nuevoUsuarioBtn.addActionListener(this::nuevoUsuarioBtnActionPerformed);

        mostrarTodos.setBackground(new java.awt.Color(153, 153, 153));
        mostrarTodos.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        mostrarTodos.setText("Todos");
        mostrarTodos.addActionListener(this::mostrarTodosActionPerformed);

        jButton2.setBackground(new java.awt.Color(255, 51, 51));
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Regresar");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        barraBusqeuda.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        barraBusqeuda.addActionListener(this::barraBusqeudaActionPerformed);

        sucursalesBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        rolesBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin sistema", "Tendero", "Cocinero" }));
        rolesBox.addActionListener(this::rolesBoxActionPerformed);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );

        panelNuevoUsuario.setBackground(new java.awt.Color(255, 255, 51));

        javax.swing.GroupLayout panelNuevoUsuarioLayout = new javax.swing.GroupLayout(panelNuevoUsuario);
        panelNuevoUsuario.setLayout(panelNuevoUsuarioLayout);
        panelNuevoUsuarioLayout.setHorizontalGroup(
            panelNuevoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelNuevoUsuarioLayout.setVerticalGroup(
            panelNuevoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        mostrarTodos1.setBackground(new java.awt.Color(153, 153, 153));
        mostrarTodos1.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        mostrarTodos1.setText("Todos");
        mostrarTodos1.addActionListener(this::mostrarTodos1ActionPerformed);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("ROL:");

        sucursalLbl.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        sucursalLbl.setForeground(new java.awt.Color(0, 0, 0));
        sucursalLbl.setText("Sucursal:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelNuevoUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(247, Short.MAX_VALUE)
                .addComponent(nuevoUsuarioBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(223, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rolesBox, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(sucursalesBox, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(barraBusqeuda, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(mostrarTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mostrarTodos1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(sucursalLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nuevoUsuarioBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(sucursalLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sucursalesBox, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rolesBox, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(barraBusqeuda, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mostrarTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mostrarTodos1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelNuevoUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nuevoUsuarioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoUsuarioBtnActionPerformed
        this.panelNuevoUsuario.setLayout(new BorderLayout());
        this.panelNuevoUsuario.add(new UsuarioForm(this.panelNuevoUsuario), BorderLayout.CENTER);
        this.revalidate();
        this.repaint();

        /*this.panelResultados.removeAll();
        this.panelResultados.setLayout(new BorderLayout());
        this.panelResultados.add(new NuevaSucursalPanel(this.panelResultados), BorderLayout.NORTH);
        this.panelResultados.revalidate();
        this.panelResultados.repaint();
        this.revalidate();
        this.repaint();*/
    }//GEN-LAST:event_nuevoUsuarioBtnActionPerformed

    private void mostrarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarTodosActionPerformed

    }//GEN-LAST:event_mostrarTodosActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.padre.regresar();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void barraBusqeudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barraBusqeudaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barraBusqeudaActionPerformed

    private void mostrarTodos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarTodos1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mostrarTodos1ActionPerformed

    private void rolesBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rolesBoxActionPerformed
       this.cambiarVisivilidadSucursales();
    }//GEN-LAST:event_rolesBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField barraBusqeuda;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton mostrarTodos;
    private javax.swing.JButton mostrarTodos1;
    private javax.swing.JButton nuevoUsuarioBtn;
    private javax.swing.JPanel panelNuevoUsuario;
    private javax.swing.JComboBox<String> rolesBox;
    private javax.swing.JLabel sucursalLbl;
    private javax.swing.JComboBox<String> sucursalesBox;
    // End of variables declaration//GEN-END:variables
}
