/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.pizzaexpress.frontend.panels_por_rol.super_admin;

import com.mycompany.pizzaexpress.frontend.sucursales.SucursalesPanel;
import java.awt.BorderLayout;

/**
 *
 * @author edu
 */
public class PanelBase_SuperAdmin extends javax.swing.JPanel {

    /**
     * Creates new form PanelBase_SuperAdmin
     */
    public PanelBase_SuperAdmin() {
        initComponents();
       iniciarPanel();
    }
    
    
    private void iniciarPanel(){
        this.setLayout(new BorderLayout());
        this.add(new SuperAdminPanel(this), BorderLayout.CENTER);
        this.revalidate();
        this.repaint();
    }
    
    
    
    public void cambiarASucursales(){
        limpiarFrame();
        this.add(new SucursalesPanel(this), BorderLayout.CENTER);
    }
    
    public void limpiarFrame(){
        this.removeAll();
        this.revalidate();
        this.repaint();
    }
    
    
    public void regresar(){
        limpiarFrame();
        iniciarPanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
