/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.pizzaexpress.frontend.reportes;

import com.mycompany.pizzaexpress.backend.modelos.reportes.PartidaReporte;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author edu
 */
public class TablaPartidas extends javax.swing.JPanel {

    /**
     * Creates new form TablaRanking
     */
    public TablaPartidas(ArrayList<PartidaReporte> partidas) {
        initComponents();
        this.cargarTablaPartidas(partidas);
        this.revalidate();
        this.repaint();
        this.componerTabla();
    }

    private void cargarTablaPartidas(ArrayList<PartidaReporte> partidas) {
        DefaultTableModel modelo = (DefaultTableModel) tablaPartida.getModel();
        modelo.setRowCount(0);

        for (PartidaReporte p : partidas) {
                Object[] fila = new Object[11];
            fila[0] = p.getNombreSucursal();
            fila[1] = p.getNombreUsuario();
            fila[2] = p.getNickname();
            fila[3] = p.getNivelAlcanzado();
            fila[4] = p.getPenalizaciones();
            fila[5] = p.getPedidosExitosos();
            fila[6] = p.getPedidosIncompletos();
            fila[7] = p.getPedidosCancelados();
            fila[8] = p.getBonosEficiencia();
            fila[9] = p.getPuntosTotales();
            fila[10] = p.getFecha();
            modelo.addRow(fila);
        }
    }
    private void componerTabla(){
        tablaPartida.getTableHeader().setFont(new java.awt.Font("SansSerif", java.awt.Font.BOLD, 18));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPartida = new javax.swing.JTable();

        tablaPartida.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        tablaPartida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "SUCURSAL", "Jugador", "Nickname", "Nivel max", "Penalizaciones", "Entregados", "Incompletos", "Cancelados", "Bonos eficiencia", "Total", "Fecha"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaPartida.setOpaque(false);
        tablaPartida.setRowHeight(35);
        tablaPartida.setRowMargin(1);
        jScrollPane1.setViewportView(tablaPartida);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1186, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaPartida;
    // End of variables declaration//GEN-END:variables
}
