/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.pizzaexpress.frontend.usuarios;
import com.mycompany.pizzaexpress.backend.exceptions.ExceptionGenerica;
import com.mycompany.pizzaexpress.backend.modelos.Usuario;
import com.mycompany.pizzaexpress.backend.servicios.UsuariosCrudService;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author edu
 */
public class UsuarioInfo extends javax.swing.JPanel {
    private JPanel panelContenedor;
    private UsuariosPanel usuariosPanel;
    private UsuariosPanel superPadre;
    private JPanel panelResultados;
    private JPanel panelDeFormulario;
    private Usuario usuario;
    private UsuariosCrudService crudService = new UsuariosCrudService();

    /**
     * Creates new form TablaSucursales
     */
    public UsuarioInfo(Usuario usuario, UsuariosPanel usuariosPanel, JPanel panelContenedor ) {
        initComponents();
        this.usuario = usuario;
        this.panelContenedor = panelContenedor;
        this.usuariosPanel= usuariosPanel;
        rellenarDatos();
    }

    private void rellenarDatos() {
       this.nombreLbl.setText(usuario.getNombre());
       this.rolLbl.setText(usuario.getRol());
       this.nicknameLbl.setText(usuario.getNickname());
       if(usuario.getRol().equals("ADMIN_SISTEMA")){
           this.sucursalLbl.setVisible(false);
           this.sucursalTitulo.setVisible(false);
       }else{
           this.sucursalLbl.setText(usuario.getNombreSucursal());
       }
    }
    
    
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        editarLbl = new javax.swing.JButton();
        eliminarLbl = new javax.swing.JButton();
        nombreTitulo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        rolTitulo = new javax.swing.JLabel();
        sucursalTitulo = new javax.swing.JLabel();
        nombreLbl = new javax.swing.JLabel();
        rolLbl = new javax.swing.JLabel();
        sucursalLbl = new javax.swing.JLabel();
        sucursalTitulo1 = new javax.swing.JLabel();
        nicknameLbl = new javax.swing.JLabel();

        jLabel5.setFont(new java.awt.Font("Fira Sans", 1, 24)); // NOI18N
        jLabel5.setText("Nombre:");

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        editarLbl.setBackground(new java.awt.Color(102, 153, 255));
        editarLbl.setFont(new java.awt.Font("Fira Sans", 0, 24)); // NOI18N
        editarLbl.setForeground(new java.awt.Color(0, 0, 0));
        editarLbl.setText("Editar");
        editarLbl.addActionListener(this::editarLblActionPerformed);

        eliminarLbl.setBackground(new java.awt.Color(255, 102, 102));
        eliminarLbl.setFont(new java.awt.Font("Fira Sans", 0, 24)); // NOI18N
        eliminarLbl.setForeground(new java.awt.Color(0, 0, 0));
        eliminarLbl.setText("Eliminar");
        eliminarLbl.addActionListener(this::eliminarLblActionPerformed);

        nombreTitulo.setFont(new java.awt.Font("Fira Sans", 1, 24)); // NOI18N
        nombreTitulo.setText("Nombre:");

        jLabel3.setFont(new java.awt.Font("Fira Sans", 1, 18)); // NOI18N

        rolTitulo.setFont(new java.awt.Font("Fira Sans", 1, 24)); // NOI18N
        rolTitulo.setText("Rol:");

        sucursalTitulo.setFont(new java.awt.Font("Fira Sans", 1, 24)); // NOI18N
        sucursalTitulo.setText("Sucursal:");

        nombreLbl.setFont(new java.awt.Font("Fira Sans", 0, 24)); // NOI18N
        nombreLbl.setForeground(new java.awt.Color(0, 0, 0));
        nombreLbl.setText("jLabel8");

        rolLbl.setFont(new java.awt.Font("Fira Sans", 0, 24)); // NOI18N
        rolLbl.setForeground(new java.awt.Color(0, 0, 0));
        rolLbl.setText("jLabel8");

        sucursalLbl.setFont(new java.awt.Font("Fira Sans", 0, 24)); // NOI18N
        sucursalLbl.setForeground(new java.awt.Color(0, 0, 0));
        sucursalLbl.setText("jLabel8");

        sucursalTitulo1.setFont(new java.awt.Font("Fira Sans", 1, 24)); // NOI18N
        sucursalTitulo1.setText("Nickname");

        nicknameLbl.setFont(new java.awt.Font("Fira Sans", 0, 24)); // NOI18N
        nicknameLbl.setForeground(new java.awt.Color(0, 0, 0));
        nicknameLbl.setText("jLabel8");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombreTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sucursalTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rolTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sucursalTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rolLbl)
                            .addComponent(sucursalLbl)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nombreLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(eliminarLbl)
                        .addGap(27, 27, 27)
                        .addComponent(editarLbl))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nicknameLbl)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreTitulo)
                    .addComponent(nombreLbl))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(editarLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(eliminarLbl)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rolTitulo)
                            .addComponent(rolLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sucursalTitulo)
                            .addComponent(sucursalLbl))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sucursalTitulo1)
                    .addComponent(nicknameLbl))
                .addContainerGap(30, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void eliminarLblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarLblActionPerformed
        
        int opcion = JOptionPane.showConfirmDialog(this, "Desea eliminar a "+ usuario.getNombre()+ " ?");
        if(opcion == JOptionPane.YES_OPTION){
            try {
                this.crudService.eliminar(usuario.getId());
                this.panelContenedor.remove(this);
                this.panelContenedor.revalidate();
                this.panelContenedor.repaint();
            } catch (ExceptionGenerica ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }
    }//GEN-LAST:event_eliminarLblActionPerformed

    private void editarLblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarLblActionPerformed
       this.usuariosPanel.mostrarEdicionForm(usuario);
    }//GEN-LAST:event_editarLblActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editarLbl;
    private javax.swing.JButton eliminarLbl;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel nicknameLbl;
    private javax.swing.JLabel nombreLbl;
    private javax.swing.JLabel nombreTitulo;
    private javax.swing.JLabel rolLbl;
    private javax.swing.JLabel rolTitulo;
    private javax.swing.JLabel sucursalLbl;
    private javax.swing.JLabel sucursalTitulo;
    private javax.swing.JLabel sucursalTitulo1;
    // End of variables declaration//GEN-END:variables
}
